export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const LOCALE_SET = "LOCALE_SET";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_RESTAURANT_NAME = "UPDATE_RESTAURANT_NAME";
export const UPDATE_ORDER_MENU = "UPDATE_ORDER_MENU";
export const UPDATE_MIN_PRICE = "UPDATE_MIN_PRICE";
export const UPDATE_TRIGGER_MYRESTAURANT = "UPDATE_TRIGGER_MYRESTAURANT";
export const UPDATE_TRIGGER_RESCOMPONENT = "UPDATE_TRIGGER_RESCOMPONENT";
export const TRIGGER_LOGIN_SIGNUP_BUTTON_HEADER =
  "TRIGGER_LOGIN_SIGNUP_BUTTON_HEADER";

export const UPDATE_ORDER_TEL = "UPDATE_ORDER_TEL";
